from datetime import datetime, UTC
from uuid import uuid4

from sqlalchemy import (
    JSON,
    DateTime,
    Enum,
    ForeignKey,
    String,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base
from app.schemas.execution import ApprovalStatus


class ExecutionRecordModel(Base):
    """
    Persisted execution workflow record.
    Generated by Execution Agent after RFQ creation
    and approval routing.
    """

    __tablename__ = "execution_records"

    id: Mapped[str] = mapped_column(
        String(64),
        primary_key=True,
        default=lambda: str(uuid4()),
    )

    execution_id: Mapped[str] = mapped_column(
        String(128),
        nullable=False,
        unique=True,
        index=True,
    )

    mitigation_plan_id: Mapped[str] = mapped_column(
        ForeignKey("mitigation_plans.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    rfq_ids: Mapped[list] = mapped_column(
        JSON,
        nullable=False,
        default=list,
    )

    approval_status: Mapped[ApprovalStatus] = mapped_column(
        Enum(ApprovalStatus),
        nullable=False,
        index=True,
    )

    approval_decision_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    approved_by: Mapped[str | None] = mapped_column(
        String(120),
        nullable=True,
    )

    dispatch_log: Mapped[list] = mapped_column(
        JSON,
        nullable=False,
        default=list,
    )

    response_log: Mapped[list] = mapped_column(
        JSON,
        nullable=False,
        default=list,
    )

    created_by_agent: Mapped[str] = mapped_column(
        String(120),
        default="execution_agent",
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        nullable=False,
        index=True,
    )