from datetime import datetime, UTC
from uuid import uuid4

from sqlalchemy import (
    JSON,
    DateTime,
    Enum,
    ForeignKey,
    Integer,
    String,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base
from app.schemas.execution import RFQStatus


class RFQRecord(Base):
    """
    Persisted RFQ generated by Execution Agent.
    """

    __tablename__ = "rfqs"

    id: Mapped[str] = mapped_column(
        String(64),
        primary_key=True,
        default=lambda: str(uuid4()),
    )

    mitigation_plan_id: Mapped[str] = mapped_column(
        ForeignKey("mitigation_plans.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    rfq_id: Mapped[str] = mapped_column(
        String(128),
        nullable=False,
        unique=True,
        index=True,
    )

    supplier_id: Mapped[str] = mapped_column(
        ForeignKey("suppliers.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    supplier_name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    supplier_email: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    line_items: Mapped[list] = mapped_column(
        JSON,
        nullable=False,
        default=list,
    )

    response_deadline: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
    )

    delivery_destination: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    terms_ref: Mapped[str] = mapped_column(
        String(120),
        nullable=False,
    )

    status: Mapped[RFQStatus] = mapped_column(
        Enum(RFQStatus),
        default=RFQStatus.DRAFT,
        nullable=False,
        index=True,
    )

    version: Mapped[int] = mapped_column(
        Integer,
        default=1,
        nullable=False,
    )

    generated_by: Mapped[str] = mapped_column(
        String(120),
        default="execution_agent",
        nullable=False,
    )

    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        nullable=False,
    )