from datetime import datetime, UTC
from uuid import uuid4

from sqlalchemy import (
    JSON,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base
from app.schemas.assessments import RiskLevel


class RiskAssessmentRecord(Base):
    """
    Persisted supplier risk assessment.
    Generated by Risk Analyst Agent.
    """

    __tablename__ = "risk_assessments"

    id: Mapped[str] = mapped_column(
        String(64),
        primary_key=True,
        default=lambda: str(uuid4()),
    )

    supplier_id: Mapped[str] = mapped_column(
        ForeignKey("suppliers.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    score: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    level: Mapped[RiskLevel] = mapped_column(
        Enum(RiskLevel),
        nullable=False,
        index=True,
    )

    factor_breakdown: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=dict,
    )

    contributing_signals: Mapped[list] = mapped_column(
        JSON,
        nullable=False,
        default=list,
    )

    anomaly_detected: Mapped[bool] = mapped_column(
        default=False,
        nullable=False,
    )

    anomaly_data: Mapped[dict | None] = mapped_column(
        JSON,
        nullable=True,
    )

    reasoning_summary: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    assessed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        nullable=False,
        index=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        nullable=False,
    )