"""create initial supplychain guardian tables

Revision ID: 1d1527e8b0a1
Revises: 
Create Date: 2026-05-08 15:08:05.010099

"""

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1d1527e8b0a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('log_id', sa.String(length=128), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=120), nullable=False),
    sa.Column('agent_version', sa.String(length=50), nullable=False),
    sa.Column('execution_record_id', sa.String(length=128), nullable=False),
    sa.Column('input_hash', sa.String(length=128), nullable=False),
    sa.Column('sanctions_results', sa.JSON(), nullable=False),
    sa.Column('regulatory_results', sa.JSON(), nullable=False),
    sa.Column('verdict', sa.Enum('CLEARED', 'FLAGGED', 'BLOCKED', name='complianceverdict'), nullable=False),
    sa.Column('verdict_rationale', sa.Text(), nullable=False),
    sa.Column('llm_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_audit_logs'))
    )
    op.create_index(op.f('ix_compliance_audit_logs_created_at'), 'compliance_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_compliance_audit_logs_execution_record_id'), 'compliance_audit_logs', ['execution_record_id'], unique=False)
    op.create_index(op.f('ix_compliance_audit_logs_input_hash'), 'compliance_audit_logs', ['input_hash'], unique=False)
    op.create_index(op.f('ix_compliance_audit_logs_log_id'), 'compliance_audit_logs', ['log_id'], unique=True)
    op.create_index(op.f('ix_compliance_audit_logs_verdict'), 'compliance_audit_logs', ['verdict'], unique=False)
    op.create_index(op.f('ix_compliance_audit_logs_workflow_run_id'), 'compliance_audit_logs', ['workflow_run_id'], unique=False)
    op.create_table('mitigation_weight_configs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('cost_delta_weight', sa.Float(), nullable=False),
    sa.Column('lead_time_weight', sa.Float(), nullable=False),
    sa.Column('residual_risk_weight', sa.Float(), nullable=False),
    sa.Column('onboarding_weight', sa.Float(), nullable=False),
    sa.Column('confidence_weight', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mitigation_weight_configs'))
    )
    op.create_table('risk_weight_configs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('financial_weight', sa.Float(), nullable=False),
    sa.Column('geopolitical_weight', sa.Float(), nullable=False),
    sa.Column('logistics_weight', sa.Float(), nullable=False),
    sa.Column('weather_weight', sa.Float(), nullable=False),
    sa.Column('tariff_weight', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_weight_configs'))
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('product_categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('certifications', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DORMANT', 'SUSPENDED', 'INACTIVE', name='supplierstatus'), nullable=False),
    sa.Column('compliance_status', sa.Enum('APPROVED', 'PENDING_REVIEW', 'EXCLUDED', 'BLOCKED', name='compliancestatus'), nullable=False),
    sa.Column('relationship_status', sa.Enum('ACTIVE_SECONDARY', 'DORMANT', 'NEW', name='relationshipstatus'), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('typical_lead_time_days', sa.Integer(), nullable=True),
    sa.Column('capacity_units_per_month', sa.Integer(), nullable=True),
    sa.Column('on_time_delivery_rate', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('latest_risk_score', sa.Float(), nullable=True),
    sa.Column('supplier_profile_text', sa.Text(), nullable=True),
    sa.Column('embedding_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_index(op.f('ix_suppliers_country'), 'suppliers', ['country'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_region'), 'suppliers', ['region'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('config_key', sa.String(length=255), nullable=False),
    sa.Column('config_value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_configs'))
    )
    op.create_index(op.f('ix_system_configs_config_key'), 'system_configs', ['config_key'], unique=True)
    op.create_table('mitigation_plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('original_supplier_id', sa.String(length=64), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('recommended_options', sa.JSON(), nullable=False),
    sa.Column('candidate_suppliers', sa.JSON(), nullable=False),
    sa.Column('simulated_scenarios', sa.JSON(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('created_by_agent', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['original_supplier_id'], ['suppliers.id'], name=op.f('fk_mitigation_plans_original_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mitigation_plans'))
    )
    op.create_index(op.f('ix_mitigation_plans_created_at'), 'mitigation_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_mitigation_plans_original_supplier_id'), 'mitigation_plans', ['original_supplier_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('factor_breakdown', sa.JSON(), nullable=False),
    sa.Column('contributing_signals', sa.JSON(), nullable=False),
    sa.Column('anomaly_detected', sa.Boolean(), nullable=False),
    sa.Column('anomaly_data', sa.JSON(), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_risk_assessments_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_assessments'))
    )
    op.create_index(op.f('ix_risk_assessments_assessed_at'), 'risk_assessments', ['assessed_at'], unique=False)
    op.create_index(op.f('ix_risk_assessments_level'), 'risk_assessments', ['level'], unique=False)
    op.create_index(op.f('ix_risk_assessments_supplier_id'), 'risk_assessments', ['supplier_id'], unique=False)
    op.create_table('execution_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=128), nullable=False),
    sa.Column('mitigation_plan_id', sa.String(length=64), nullable=False),
    sa.Column('rfq_ids', sa.JSON(), nullable=False),
    sa.Column('approval_status', sa.Enum('AUTO_APPROVED', 'PENDING_HUMAN', 'HUMAN_APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('approval_decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('dispatch_log', sa.JSON(), nullable=False),
    sa.Column('response_log', sa.JSON(), nullable=False),
    sa.Column('created_by_agent', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mitigation_plan_id'], ['mitigation_plans.id'], name=op.f('fk_execution_records_mitigation_plan_id_mitigation_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_records'))
    )
    op.create_index(op.f('ix_execution_records_approval_status'), 'execution_records', ['approval_status'], unique=False)
    op.create_index(op.f('ix_execution_records_created_at'), 'execution_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_execution_records_execution_id'), 'execution_records', ['execution_id'], unique=True)
    op.create_index(op.f('ix_execution_records_mitigation_plan_id'), 'execution_records', ['mitigation_plan_id'], unique=False)
    op.create_table('rfqs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mitigation_plan_id', sa.String(length=64), nullable=False),
    sa.Column('rfq_id', sa.String(length=128), nullable=False),
    sa.Column('supplier_id', sa.String(length=64), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('supplier_email', sa.String(length=255), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=False),
    sa.Column('response_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_destination', sa.String(length=255), nullable=False),
    sa.Column('terms_ref', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'DISPATCHED', 'RESPONDED', 'EXPIRED', 'CANCELLED', name='rfqstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.String(length=120), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mitigation_plan_id'], ['mitigation_plans.id'], name=op.f('fk_rfqs_mitigation_plan_id_mitigation_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_rfqs_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rfqs'))
    )
    op.create_index(op.f('ix_rfqs_mitigation_plan_id'), 'rfqs', ['mitigation_plan_id'], unique=False)
    op.create_index(op.f('ix_rfqs_response_deadline'), 'rfqs', ['response_deadline'], unique=False)
    op.create_index(op.f('ix_rfqs_rfq_id'), 'rfqs', ['rfq_id'], unique=True)
    op.create_index(op.f('ix_rfqs_status'), 'rfqs', ['status'], unique=False)
    op.create_index(op.f('ix_rfqs_supplier_id'), 'rfqs', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rfqs_supplier_id'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_status'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_rfq_id'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_response_deadline'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_mitigation_plan_id'), table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_index(op.f('ix_execution_records_mitigation_plan_id'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_execution_id'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_created_at'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_approval_status'), table_name='execution_records')
    op.drop_table('execution_records')
    op.drop_index(op.f('ix_risk_assessments_supplier_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_level'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_assessed_at'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_mitigation_plans_original_supplier_id'), table_name='mitigation_plans')
    op.drop_index(op.f('ix_mitigation_plans_created_at'), table_name='mitigation_plans')
    op.drop_table('mitigation_plans')
    op.drop_index(op.f('ix_system_configs_config_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_suppliers_region'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_country'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('risk_weight_configs')
    op.drop_table('mitigation_weight_configs')
    op.drop_index(op.f('ix_compliance_audit_logs_workflow_run_id'), table_name='compliance_audit_logs')
    op.drop_index(op.f('ix_compliance_audit_logs_verdict'), table_name='compliance_audit_logs')
    op.drop_index(op.f('ix_compliance_audit_logs_log_id'), table_name='compliance_audit_logs')
    op.drop_index(op.f('ix_compliance_audit_logs_input_hash'), table_name='compliance_audit_logs')
    op.drop_index(op.f('ix_compliance_audit_logs_execution_record_id'), table_name='compliance_audit_logs')
    op.drop_index(op.f('ix_compliance_audit_logs_created_at'), table_name='compliance_audit_logs')
    op.drop_table('compliance_audit_logs')
    # ### end Alembic commands ###