"""add supplier risk history table

Revision ID: f16030eddb4c
Revises: 1d1527e8b0a1
Create Date: 2026-05-08 18:08:55.073511

"""

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision = 'f16030eddb4c'
down_revision = '1d1527e8b0a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_risk_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('supplier_id', sa.String(length=64), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_risk_history_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_risk_history'))
    )
    op.create_index(op.f('ix_supplier_risk_history_assessed_at'), 'supplier_risk_history', ['assessed_at'], unique=False)
    op.create_index(op.f('ix_supplier_risk_history_supplier_id'), 'supplier_risk_history', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_risk_history_supplier_id'), table_name='supplier_risk_history')
    op.drop_index(op.f('ix_supplier_risk_history_assessed_at'), table_name='supplier_risk_history')
    op.drop_table('supplier_risk_history')
    # ### end Alembic commands ###