from datetime import datetime

from pydantic import Field

from app.schemas.common import BaseSchema


class SimulatedScenario(BaseSchema):
    """
    Result of simulating a supplier switch.
    """

    supplier_id: str
    supplier_name: str

    cost_delta_pct: float = Field(
        ...,
        description="Percentage cost difference vs current supplier",
    )

    lead_time_delta_days: int = Field(
        ...,
        description="Lead time difference in days",
    )

    residual_risk_score: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Expected risk score after switching",
    )

    onboarding_weeks: int = Field(
        ...,
        ge=0,
    )

    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
    )

    breakdown: dict = Field(
        default_factory=dict,
        description="Raw simulation inputs and calculations",
    )


class RecommendedOption(BaseSchema):
    """
    Ranked supplier recommendation.
    """

    rank: int

    supplier_id: str

    topsis_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
    )

    cost_delta_pct: float
    lead_time_delta_days: int

    residual_risk_score: float = Field(
        ...,
        ge=0.0,
        le=100.0,
    )

    onboarding_weeks: int

    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
    )


class MitigationPlan(BaseSchema):
    """
    Final mitigation strategy generated by Agent 2.
    """

    id: str | None = None

    original_supplier_id: str

    risk_score: float = Field(
        ...,
        ge=0.0,
        le=100.0,
    )

    recommended_options: list[RecommendedOption] = Field(
        default_factory=list
    )

    justification: str

    created_at: datetime = Field(
        default_factory=datetime.utcnow
    )


class MitigationSummary(BaseSchema):
    """
    Lightweight dashboard summary.
    """

    original_supplier_id: str

    total_candidates: int

    recommended_supplier_id: str | None = None

    expected_cost_delta_pct: float | None = None

    expected_risk_reduction: float | None = None

    generated_at: datetime = Field(
        default_factory=datetime.utcnow
    )